name: myapps
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  logger: ^2.0.2+1
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.0.0
  shared_preferences: ^2.2.2
  auto_route: ^6.2.0
  device_info_plus: ^9.1.1
  dio: ^5.0.0
  intl: ^0.19.0
  image_picker: ^0.8.4+4
#  geolocator: ^14.0.0
  battery_plus: ^6.2.1
  cached_network_image: ^3.2.0
  get_it: ^7.6.4
  supabase_flutter: ^2.8.4
  shimmer: ^3.0.0
  flutter_easyloading: ^3.0.5
  infinite_scroll_pagination: ^3.2.0
  pull_to_refresh: ^2.0.0
  google_fonts: ^6.2.1
  responsive_framework: ^0.2.0
  animations: ^2.0.1
  flutter_spinkit: ^5.1.0
  permission_handler: ^11.1.0
  overlay_support: ^1.2.1
  modal_bottom_sheet: ^2.1.2
#  firebase_core: ^3.13.0
#  firebase_messaging: ^15.2.5
#  sign_in_with_apple: ^7.0.1
#  webview_flutter: ^4.10.0
  flutter_styled_toast: ^2.2.1
  lottie: ^2.7.0
  fluttertoast: ^8.2.12
  flutter_svg: ^2.0.9
#  firebase_analytics: ^11.4.5
  connectivity_plus: ^6.1.4
  loading_animation_widget: ^1.3.0
  animated_toggle_switch: ^0.8.4
  google_sign_in: ^6.3.0
  internet_connection_checker: ^3.0.1
  hawk_fab_menu: ^1.2.0
  flutter_expandable_fab: ^2.5.1
  pull_to_refresh_flutter3: ^2.0.2
  dropdown_search: ^6.0.2
  custom_refresh_indicator: ^4.0.1
  iconify_flutter_plus: ^1.0.4
#  esc_pos_utils: ^1.0.2
  buttons_tabbar: ^1.3.15
  flutter_staggered_animations: ^1.1.1
  flutter_slidable: ^4.0.0
  floating_tabbar: ^1.0.3
  flutter_floating_bottom_bar: ^1.3.0
  blue_thermal_printer: ^1.1.5

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  freezed: ^2.0.0
  auto_route_generator: ^6.2.0
  flutter_lints: ^5.0.0
  pretty_dio_logger: ^1.3.1
  analyzer: ^5.9.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/maxclean/logo_max_clean.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/anims/
    - assets/fonts/
    - assets/audios/
    - assets/images/
    - assets/maxclean/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/nunito-regular.ttf
          weight: 400
        - asset: assets/fonts/nunito/nunito-bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
    - family: WorkSans
      fonts:
        - asset: assets/fonts/worksans/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/worksans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/worksans/WorkSans-Bold.ttf
          weight: 700
    - family: JakartaSans
      fonts:
        - asset: assets/fonts/jakarta/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/jakarta/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/jakarta/jakarta-bold.ttf
          weight: 700
        - asset: assets/fonts/jakarta/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/jakarta/PlusJakartaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/jakarta/PlusJakartaSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
